name: Support Ticket
description: Submit a new support ticket for this project
title: "[SUPPORT] "
labels: [support]

body:
  - type: markdown
    attributes:
      value: |
        ## Please describe your support request in detail.

  - type: input
    id: support-ticket-title
    attributes:
      label: Support Ticket Title
      placeholder: Enter the title of your support request

  - type: textarea
    id: support-ticket-description
    attributes:
      label: Support Ticket Description
      description: Please describe the issue or request in detail
      placeholder: Describe the issue or request...

  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional Information
      description: Check if you have additional information to provide
      options:
        - label: I have additional information