# Create a simple issue template and choose assignees and labels
name: Create simple issue
description: Use this template to describe your issue and possible fixes that you have try already.
body:
  - type: markdown
    attributes:
      value: |
        ## Add a title for your issue
        #### If possible, please take a screenshot of your problem also and attach it to this issue-description

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the issue
      placeholder: Please, describe the issue...