name: Create issue
description: Use this template to describe your issue and possible fixes that you have try already.
body:
  - type: markdown
    attributes:
      value: |
        ## Please describe your issue and possible fixes that you have try already.

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the issue
      placeholder: Please, describe the issue...

  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional Information
      description: Check if you have additional information to provide
      options:
        - label: I have additional information